### ISSUE TITLE
Longer nicks overflow on two lines

### ISSUE THREAD

**Issue by TheSonAlsoRises** [thelounge/lounge#577]
![tln5exm](https://cloud.githubusercontent.com/assets/8591366/17857067/9ef38dc8-6880-11e6-912d-9c381a30f9f6.png)

Long nicknames are going overflow a second line, which makes reading the conversation harder than it should be.

**Comment by xPaw** [comment]
Should be fixed by #523

**Comment by astorije** [comment]
@TheSonAlsoRises, could you check if this issue still exists on `master`? #523 was merged and hopefully this is not an issue anymore.

**Comment by YaManicKill** [comment]
It does still happen, just tested after #523 merge.

Fwiw, there are very few servers that support names long enough for this. Synirc is the one we both use for that.

I have a small css tweak that fixes it, but it's not perfect. Once [text-overflow: fade](https://developer.mozilla.org/en/docs/Web/CSS/text-overflow) is supported, I can sort this out in a really nice way, but currently it either involves a horrible fade with ::after, or the name just cutting off. Or using JS. Don't want to use any of these solutions.

```css
/* Truncate username */

#chat .message .from {
  overflow: hidden;
  white-space: nowrap;
}

#chat .message .from:after {
    left: calc(10% - 33px);
    content: '';
    position: absolute;
    top: 0;
    width: 30px;
    height: 100%;
    background-image: linear-gradient(to left, rgba(0, 43, 54, 1), rgba(0, 43, 54, 0));
}
```
